remote_theme: christianezeani/panthera-jekyll
title: Roberto Flórez Ablan
subtitle: Estudante de Física
description: Pequeno Portafolio

left_side:
  background_image: "./assets/images/merida.jpg"
  text_color: "#000000"
