remote_theme: christianezeani/panthera-jekyll
title: Roberto Flórez Ablan
subtitle: Estudante de Física
description: Pequeno Portafolio

left_side:
  background_image: "./assets/images/merida.jpg"
  background_color: "#F00"
  close_button_color: "#F00"
  text_color: "#F00"
